spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qanda?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    username: root
    password: 961124
  mvc:
    view:
      suffix: .html
      prefix: /page/
    static-path-pattern: /**
  session:
    store-type: redis
    timeout: 1800
    redis:
      flush-mode: on_save
      namespace: spring_session

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:

mybatis:
  mapper-locations: classpath:com/teiphu/mapper/*.xml
  type-aliases-package: com.teiphu.pojo


